services:
  flask-app:
    build:
      context: ../              
      dockerfile: docker/Dockerfile  
    ports:
      - "8080:8080"             
    volumes:
      - ../:/app         
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/db_measurements
      - FLASK_APP=app.main
      - PYTHONPATH=/app     
    depends_on:
      - db
    networks:
      - app-network
  db:
    container_name: fase3_db
    build:
      context: ./postgres
    environment:
      POSTGRES_DB: db_measurements
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network: